"""
This program can be used to check individual chunks generated by a RAG system. 

"""


import os
import json
import time
from collections import defaultdict

from langchain.text_splitter import RecursiveCharacterTextSplitter

from langchain.docstore.document import Document

from langchain_community.vectorstores import FAISS
from langchain.prompts import PromptTemplate


from langchain_ollama import OllamaLLM
from langchain_openai import ChatOpenAI, OpenAIEmbeddings

from openai import OpenAI

from questions import rag_questions, INSTRUCTIONS_DICT, TEMPLATE
from constants import *

if GPT_KEY == '':
    print("Enter OPENAI API key in constants.py file")
    exit()

with open("portfolio.json", 'r') as file:
        cve_portfolios = json.load(file)


def ret_documents(discussions):
    documents = []
    for source, discussion in discussions.items():
        if source == "ubuntu":
            doc = Document(discussion["value"], metadata = {"source": source})
            documents.append(doc)
        elif source == "redhat-bugzilla":
            data = discussion[0]
            for comment in data["comments"]:
                doc = Document(comment["comment_content"], metadata = {"source":source})
                documents.append(doc)
        else:
            for disc in discussion:
                doc = Document(disc,  metadata={"source": source})
                documents.append(doc)
    
    return documents


# RAG requirements:
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=1000,
    chunk_overlap=100,
    separators=["\n\n", "\n", " ", "", "```"],  # tries to split at sensible places
    add_start_index=True
)

embedding_model = OpenAIEmbeddings(api_key=GPT_KEY)


# llm = OllamaLLM(model = "llama3:70b", temperature = 0)
llm = ChatOpenAI(
    api_key=GPT_KEY,
    model_name="gpt-4o",
    temperature=0.0,
    max_tokens=None,
).bind(logprobs = True)

prompt = PromptTemplate(template=TEMPLATE, input_variables=["question","instructions", "context"])

cve = "CVE-2022-24122"
portfolio = cve_portfolios[cve]

answer_dict = defaultdict(lambda: defaultdict(dict))
discussions = portfolio[INTRINSIC_ATTRIBS][DISCUSSIONS]
documents = []

# adding vulnerability description to the documents:
for source, desc in portfolio[INTRINSIC_ATTRIBS]["Vulnerability Description"].items():
    doc = Document(desc, metadata = {"source": source})
    documents.append(doc)

# checking and extracting vulnerable source code:
if len(portfolio[INTRINSIC_ATTRIBS][VULN_LOCATION]["Vulnerable code block"]) != 0:
    vuln_code = ""
    for codes in portfolio[INTRINSIC_ATTRIBS][VULN_LOCATION]["Vulnerable code block"]:
        if isinstance(codes, list):
            for code in codes:
                vuln_code += "\n\n" + code
        elif isinstance(code, str):
            vuln_code += "\n\n" + codes
    doc = Document("VULNERABLE CODE BLOCK: \n"+vuln_code, metadata= {"source": "Vulnerable code"})
    answer_dict["Vulnerability"]["Vulnerable code"]["portfolio"] = vuln_code
else:
    answer_dict["Vulnerability"]["Vulnerable code"]["portfolio"] = ""

# adding patch message to the documents
if len(portfolio[PATCH_SET]) != 0:
    patch_message = "[PATCH MESSAGE] \n"
    for message in portfolio[PATCH_SET]["Patch Message"]:
        if isinstance(message, list):
            for m in message:
                patch_message += "\n" + m
        elif isinstance(message, str):
            patch_message += "\n" + message 
    doc = Document(patch_message, metadata = {"source": "patch message"})
    documents.append(doc)
    doc = Document(" [PATCH CODE] \n" + str(portfolio[PATCH_SET]["Patch Code"]), metadata = {"source": "patch code"})
    documents.append(doc)
    doc = Document(" [CODE DIFF] \n" + portfolio[PATCH_SET]["Code diff"][0][0], metadata = {"source": "code diff"})
    documents.append(doc)
    answer_dict["Patch"]["Patch code"]["portfolio"] = portfolio[PATCH_SET]["Patch Code"]
    answer_dict["Patch"]["Code diff"]["portfolio"] = portfolio[PATCH_SET]["Code diff"]

# adding exploit code for better understanding of the documents
if len(portfolio[EXPLOIT_SET]) != 0:
    exploit_code = ""
    for code in portfolio[EXPLOIT_SET]["Exploit Code"]:
        exploit_code += code + "\n\n"
    doc = Document(" [EXPLOIT CODE] \n" + exploit_code, metadata = {"source": "exploit code"})
    documents.append(doc)
    answer_dict["Exploit"]["Exploit Code"]["portfolio"] = exploit_code

# adding scores to the document
document = Document("IMPACT SCORES: \n" + str(portfolio[IMPACT]), metadata = {"source":"impact scores"})
documents.append(document)

documents.extend(ret_documents(discussions))
doc_chunks = text_splitter.split_documents(documents)
vector_index = FAISS.from_documents(doc_chunks, embedding_model)
retriever = vector_index.as_retriever(search_type="mmr", search_kwargs={"k": 12}) 

split_docs = text_splitter.split_documents(documents)

print("Completed creating documents..." , len(documents))

attribute = "Exploit"
column = "exploited_versions"
check_answer = False


test_prompt = rag_questions[attribute][column]
ret_docs = retriever.invoke(test_prompt)

print("\n🔍 Retrieved Chunks:")
for i, doc in enumerate(ret_docs, 1):
    print(f"\n--- Chunk {i} ---")
    print(doc.page_content)
    print(f"Metadata: {doc.metadata}")


with open("CVE-2022-2412_expl_versions_sample_chunks.txt" , 'w') as file:
    for i, doc in enumerate(ret_docs, 1):
        file.write(f"\n--- Chunk {i} ---\n")
        file.write(doc.page_content+"\n")
        file.write(f"Metadata: {doc.metadata}\n")

llm_chain = prompt | llm

def ask_with_sources(context: str, question: str, instructions: str):
    """Run retrieval + generation and return answer + source docs."""
    answer = llm_chain.invoke({
        "question": question,
        "context": context,
        "instructions": instructions,
    })
    return answer

if check_answer:
    context = "\n\n".join(d.page_content for d in ret_docs)

    test_response =  ask_with_sources(
        context=context,
        question=test_prompt,
        instructions=INSTRUCTIONS_DICT.get(column, "")
    )

    # print(test_response)
    print(test_response.response_metadata["logprobs"]["content"])